#!/bin/bash

# Get password for MariaDB
read -s -p "Enter new password for MariaDB:" password
echo ""

# Update packages
sudo apt update
sudo apt full-upgrade -y

# Install Apache and php
sudo apt install apache2 php php-cgi php-mysqli php-pear php-mbstring libapache2-mod-php php-common php-phpseclib php-mysql -y

# Install MariaDB
sudo apt install mariadb-server expect -y

# auto config MariaDB
sudo mysql_secure_installation

#expect "Enter current password for root (enter for none):" { send "\r" }
#expect "Switch to unix_socket authentication [Y/n]" { send "n\r" }
#expect "Change the root password? [Y/n]" { send "y\r" }
#expect "New password:" { send "$password\r" }
#expect "Re-enter new password:" { send "$password\r" }
#expect "Remove anonymous users? [Y/n]" { send "y\r" }
#expect "Disallow root login remotely? [Y/n]" { send "n\r" }
#expect "Remove test database and access to it? [Y/n]" { send "y\r" }
#expect "Reload privilege tables now? [Y/n]" { send "y\r" }


# Install phpMyAdmin
wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
sudo mkdir -p /usr/share/phpmyadmin
sudo chown -R www-data:www-data /usr/share/phpmyadmin
sudo tar xvf phpMyAdmin-latest-all-languages.tar.gz --strip-components=1 -C /usr/share/phpmyadmin
sudo cp /usr/share/phpmyadmin/config.sample.inc.php /usr/share/phpmyadmin/config.inc.php
sudo rm phpMyAdmin-latest-all-languages.tar.gz


# Configure Apache
sudo echo 'Alias /sql /usr/share/phpmyadmin
<Directory /usr/share/phpmyadmin>
    Options SymLinksIfOwnerMatch
    DirectoryIndex index.php

    <IfModule mod_php.c>
        <IfModule mod_mime.c>
            AddType application/x-httpd-php .php
        </IfModule>
        <FilesMatch ".+\.php$">
            SetHandler application/x-httpd-php
        </FilesMatch>

        php_value include_path .
        php_admin_value upload_tmp_dir /var/lib/phpmyadmin/tmp

        php_admin_value open_basedir /usr/share/phpmyadmin/:/etc/phpmyadmin/:/var/lib/phpmyadmin/:/usr/share/php/php-gettext/:/usr/share/php/php-php-gettext/:/usr/share/javascript/:/usr/share/php/tcpdf/:/usr/share/doc/phpmyadmin/:/usr/share/php/phpseclib/
        php_admin_value mbstring.func_overload 0
    </IfModule>
</Directory>

# Désactiver accès web sur certains dossiers
<Directory /usr/share/phpmyadmin/templates>
    Require all denied
</Directory>
<Directory /usr/share/phpmyadmin/libraries>
    Require all denied
</Directory>
<Directory /usr/share/phpmyadmin/setup/lib>
    Require all denied
</Directory>' > /etc/apache2/conf-available/phpmyadmin.conf
sudo a2enconf phpmyadmin.conf
sudo systemctl reload apache2

# Post install phpMyAdmin
blowfish_secret=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9!@#$%^&*()_+{}|:<>?=' | fold -w 32 | head -n 1)

sudo sed -i "s/\$cfg\['blowfish_secret'\] = '';/\$cfg['blowfish_secret'] = '$blowfish_secret';/" /usr/share/phpmyadmin/config.inc.php



